/*
문제: 12세 이하인 여자 환자 목록 출력하기
분류: SELECT
링크: https://school.programmers.co.kr/learn/courses/30/lessons/132201
*/

-- IF 함수 사용
SELECT  PT_NAME, PT_NO, GEND_CD, AGE,
        IF(TLNO IS NULL, 'NONE', TLNO) TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME

-- IFNULL 함수
SELECT  PT_NAME, PT_NO, GEND_CD, AGE,
        IFNULL(TLNO, 'NONE') TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME

-- COALESCE 함수
SELECT  PT_NAME, PT_NO, GEND_CD, AGE,
        COALESCE(TLNO, 'NONE') TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME
