/*
문제: 상품 별 오프라인 매출 구하기
분류: JOIN
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131533
*/

SELECT  PRODUCT_CODE,
        p.PRICE*SUM(os.SALES_AMOUNT) SALES
FROM PRODUCT p INNER JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC, 1

-- CTE 활용
WITH TOTAL_SALME_AMOUNT AS 
     (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID)
SELECT PRODUCT_CODE, (A.PRICE * B.AMOUNT) AS SALES
FROM PRODUCT AS A
JOIN TOTAL_SALME_AMOUNT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC
-- 출처: https://school.programmers.co.kr/questions/85801
