/*
문제: 조건에 맞는 도서 리스트 출력하기
분류: SELECT
링크: https://school.programmers.co.kr/learn/courses/30/lessons/144853
*/

-- YEAR 사용
SELECT  BOOK_ID,
        DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE

-- LIKE 사용
SELECT  BOOK_ID,
        DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') 'PUBLISHED_DATE'
FROM BOOK
WHERE PUBLISHED_DATE LIKE '2021%' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE

-- BETWEEN 사용
SELECT  BOOK_ID,
        DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') 'PUBLISHED_DATE'
FROM BOOK
WHERE PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE
