/*
문제: 조건에 맞는 사용자와 총 거래금액 조회하기
분류: GROUP BY
링크: https://school.programmers.co.kr/learn/courses/30/lessons/164668
*/

-- WITH문
WITH TOTAL_SALES AS (
    SELECT  WRITER_ID,
            SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE `STATUS` = 'DONE'
    GROUP BY WRITER_ID

)
SELECT  WRITER_ID, NICKNAME,
        TOTAL_SALES
FROM TOTAL_SALES ts INNER JOIN USED_GOODS_USER uu
ON ts.WRITER_ID = uu.USER_ID 
WHERE TOTAL_SALES >= 700000
ORDER BY 3

-- 내가 생각못한 having절
SELECT  WRITER_ID, NICKNAME,
        SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD ub INNER JOIN USED_GOODS_USER uu
ON ub.WRITER_ID = uu.USER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3

-- 서브쿼리문
SELECT  WRITER_ID, NICKNAME,
        TOTAL_SALES
FROM (
    SELECT  WRITER_ID,
            SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE `STATUS` = 'DONE'
    GROUP BY WRITER_ID
) ts INNER JOIN USED_GOODS_USER uu -- 서브쿼리는 하나의 별칭만 가능! (as)가 생략되어있다는 걸 기억하기!
ON ts.WRITER_ID = uu.USER_ID 
WHERE TOTAL_SALES >= 700000
ORDER BY 3

