/*
문제: 식품분류별 가장 비싼 식품의 정보 조회하기
분류: GROUP BY
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131116
*/

-- CTE & ROW_NUMBER 활용
WITH CATEGORY_PRICE AS (
    SELECT  CATEGORY, PRICE, PRODUCT_NAME,
            ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    
)
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM CATEGORY_PRICE
WHERE PRICE_RANK = 1
GROUP BY CATEGORY
ORDER BY PRICE DESC

-- CTE & MAX 활용
WITH CATEGORY_PRICE AS (
    SELECT  CATEGORY, PRICE, PRODUCT_NAME,
            MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM CATEGORY_PRICE
WHERE PRICE = MAX_PRICE
ORDER BY PRICE DESC
-- 참고: 프로그래머스 on ryo? 님 풀이

-- where 조건 서브쿼리
SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM
    FOOD_PRODUCT
WHERE
    (CATEGORY,PRICE) IN (
        SELECT CATEGORY, MAX(PRICE)
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY
        )
ORDER BY
    PRICE DESC;
-- 참고: https://school.programmers.co.kr/questions/86155
