/*
문제: 5월 식품들의 총매출 조회하기
분류: JOIN
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131116
*/

SELECT  FP.PRODUCT_ID, PRODUCT_NAME,
        SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP INNER JOIN FOOD_ORDER FO 
ON FP.PRODUCT_ID = FO.PRODUCT_ID
-- LIKE 사용
--  WHERE PRODUCE_DATE LIKE '2022-05%'
-- YEAR, MONTH 함수 사용
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
-- DATE_FORMAT 사용
-- WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
