/*
문제: 우유와 요거트가 담긴 장바구니
분류: Summer/Winter Coding(2019)
링크: https://school.programmers.co.kr/learn/courses/30/lessons/62284
*/

-- IN by 정재님
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Yogurt', 'Milk') 
  # NAME REGEXP 'Milk|Yogurt'
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2 
ORDER BY CART_ID
  
-- OR by 상규님
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt' OR NAME = 'Milk'
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2 
ORDER BY CART_ID

-- 다른 사람들 풀이
-- WITH
WITH MILK AS (
  SELECT CART_ID
  FROM CART_PRODUCTS 
  WHERE NAME = 'Milk'
)
SELECT CART_ID
FROM CART_PRODUCTS 
WHERE CART_ID IN (
  SELECT CART_ID
  FROM MILK
) AND NAME ='Yogurt'
ORDER BY CART_ID

-- GROUP BY 2번 서브쿼리
SELECT DISTINCT CART_ID
FROM (SELECT * FROM CART_PRODUCTS
      GROUP BY NAME, CART_ID
      HAVING NAME IN ('Yogurt', 'Milk')) AS a
GROUP BY CART_ID
HAVING COUNT(CART_ID) > 1
ORDER BY CART_ID;

-- COUNT() 함수 활용 방법
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING COUNT(DISTINCT CASE WHEN NAME = 'Milk' THEN 1 WHEN NAME='Yogurt' THEN 2 END) = 2
ORDER BY CART_ID

-- SUM() 함수 활용 방법
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING SUM(DISTINCT CASE WHEN NAME = 'Milk' THEN 1 WHEN NAME='Yogurt' THEN 2 ELSE 0 END) = 3
ORDER BY CART_ID
-- 출처: https://school.programmers.co.kr/questions/82883
