/*
문제: 주문량이 많은 아이스크림들 조회하기
분류: JOIN
링크: https://school.programmers.co.kr/learn/courses/30/lessons/133027
*/

-- WITH
WITH JULY_FLAVOR AS (
    SELECT  SHIPMENT_ID, FLAVOR,
            SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY 2
)
SELECT  H.FLAVOR
FROM FIRST_HALF H LEFT JOIN JULY_FLAVOR J
ON H.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3

-- CTE, 서브쿼리 X
SELECT J.FLAVOR
FROM FIRST_HALF H
RIGHT JOIN JULY J ON H.SHIPMENT_ID = J.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY H.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;
-- 여기서 right를 해야하는 이유 : july에 중복 flavor가 존재하기 때문에 기준을 right로 join해야 한다.
-- 그래서 RIGHT OUTER JOIN을 쓴 사람도 있었나봄

-- UNION
WITH TBL AS (

    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR

UNION ALL

    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM TBL
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;
-- 참고 : https://school.programmers.co.kr/questions/86235
