/*
문제: 그룹별 조건에 맞는 식당 목록 출력하기
분류: JOIN
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131124
*/

WITH MEMBER_REVIEW AS (
    SELECT  MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
SELECT  MEMBER_NAME, REVIEW_TEXT,
        DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = ( -- with문 자체를 여기 안에 서브쿼리로 넣어도 가능
    SELECT *
    FROM MEMBER_REVIEW
)
ORDER BY 3, 2

-- 나는 LIMIT 1로 풀었는데 테스트 케이스를 보니 최대 갯수인 사람이 3명 존재했다. 
-- 그래서 이렇게 최대 갯수인 사람들이 여러 명이어도 그 사람들의 리뷰를 출력할 수 있게 다시 쿼리를 짰다.

WITH MEMBER_REVIEW AS (
    SELECT  MEMBER_ID, COUNT(*) REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
REVIEW_MAX AS ( -- CTE 하나 더 추가
    SELECT MEMBER_ID
    FROM MEMBER_REVIEW
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM MEMBER_REVIEW)
)
SELECT  MEMBER_NAME, REVIEW_TEXT,
        DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT *
    FROM REVIEW_MAX
)
ORDER BY 3, 2

-- WINDOW - RANK & CTE, 서브쿼리 사용
WITH MEMBER_REVIEW AS (
    SELECT  MEMBER_ID, 
            RANK() OVER(ORDER BY COUNT(REVIEW_ID) DESC) REVIEW_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT  MEMBER_NAME, REVIEW_TEXT,
        DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM MEMBER_REVIEW
    WHERE REVIEW_RANK = 1
)
ORDER BY 3, 2
