/*
문제: 오프라인/온라인 판매 데이터 통합하기
분류: SELECT
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131537
*/

WITH MARCH_SALES AS (
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE 
    WHERE SALES_DATE LIKE '2022-03-%'
    ) UNION ALL(
    SELECT  SALES_DATE, PRODUCT_ID,
            NULL USER_ID,
            SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE '2022-03-%'
    )
)
SELECT  DATE_FORMAT(SALES_DATE, '%Y-%m-%d'), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM MARCH_SALES
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
